resources:
  repositories:
    - repository: templates
      type: github
      name: Tereius/conan-azure-templates
      endpoint: Tereius

jobs:
- job:
  pool:
    vmImage: 'windows-2019'
  timeoutInMinutes: 0
  strategy:
    matrix:
      Portable:
        portable: "True"
      Installer:
        portable: "False"
  steps:
  - template: buildConanRecipe.yml@templates
    parameters: 
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_BASE_PROFILE: "default"
        CONAN_OPTIONS: "portable=$(portable)"
      }

  - task: CopyFiles@2
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
    inputs:
      targetFolder: "$(Build.ArtifactStagingDirectory)"
      contents: "LS50Remote.*"

  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: LS50Remote
